### ISSUE TITLE
Step 4:  Eggnog_annotation RScript

### ISSUE THREAD

**Issue by hfri** [reganhayward/micromix#2]
For me it does not work to run the  R Script using ./Rscript parse_eggnog_annotations.R eggnog_annotations.csv, instead I need to use Rscript  parse_eggnog_annotations.R eggnog_annotations.csv.

The second problem that I had were dependency issues using the virtual machine. I could not run the script because dependencies were missing for the Go.db and KEGGREST package

**Comment by reganhayward** [comment]
updated and removed ./ before RScript

**Comment by reganhayward** [comment]
updated for dependencies and instructions for installing R in Ubuntu

**Comment by reganhayward** [comment]
Updates made
