### ISSUE TITLE
Modifying or adding gene or pathway annotations : Issues with the output files

### ISSUE THREAD

**Issue by hfri** [reganhayward/micromix#3]
I thought maybe it is easier, if I commented it here. Both output files gene_annotations.json and pathways.json appear to have different formats compared to the original files.

**gene_annotation.json:**
- keggID name differs (kegg_pathway_id instead of kegg_id)
- GO-terms and Kegg pathways are not separated as individual strings (e.g.,"GO:0044444,GO:0044464", not "GO:0044444", "GO:0044464")
- There is no COG output 

**pathways.json**
- different format in the two files
- original file from bacteriodes:
![original_pathway](https://user-images.githubusercontent.com/115802494/223733257-2d950e08-e24e-4ced-92be-9965be94b592.png)
-my file from salmonella:
-
![my_pathway_file](https://user-images.githubusercontent.com/115802494/223733849-f6312c9b-60b6-431b-aa0c-f213fab2d0e0.png)

**Comment by hfri** [comment]
Edit: I figured that the pathway file for the Bacteroides data is assigning the COG categories as well. He gave the categories a letter. That is why it looks different.

**Comment by reganhayward** [comment]
I've updated the R script and the sed command. It should now work.

I'll chat Monday about the COG categories

**Comment by hfri** [comment]
it works!

**Comment by reganhayward** [comment]
excellent!!
