### ISSUE TITLE
How to add new expression data: new data is not assigned to a species and not recognised by the heatmap plug in

### ISSUE THREAD

**Issue by hfri** [reganhayward/micromix#5]
I added my data and it is now displayed under "No organisms". However, it is not shown under the Salmonella button. It feels like there is a step missing that assigns it to the correct species. 
Furthermore, my data is not correctly displayed in the heatmap plug-in.  It could be that it is a problem with my data set or that I missed something. In the other data sets the column names are preceded by a combination of letters e.g.  "(zxczx) Anaerobic Growth", I was wondering if they signify some form of coordinates or so. Mine do not have these letters.

**Comment by hfri** [comment]
Found the solution to the species problem. I did not add it to the organism file. My fault!

**Comment by reganhayward** [comment]
All good!
Do you think additional info is needed in the documentation?

**Comment by hfri** [comment]
I think it would be good to mention it under the adding new expression data step as well because not everyone is adding a new organism and then you might miss the comment.

**Comment by reganhayward** [comment]
Would you mind adding the text? I can happily edit it if you want - I'm curious to see how you would word this :-)

**Comment by hfri** [comment]
will do

**Comment by hfri** [comment]
changed it
