### ISSUE TITLE
Heatmap still reads my file as string

### ISSUE THREAD

**Issue by hfri** [reganhayward/micromix#6]
I tried reordering the columns but it did not work. The columns are still read as string variables. I thought maybe it can only accept two columns (locus tag and gene name) as string variables and thereafter needs count data. So, I deleted all columns with extra descriptions except for locus_tag and gene_name. However, that did not change anything. What I noticed is that in other datasets all columns with numeric information are preceded by the name that I gave the dataset while my columns do not have that.

Other salmonella data:
![image](https://user-images.githubusercontent.com/115802494/224049842-956b393e-2cde-40d8-b743-e58244450105.png)

My data:
![Screenshot from 2023-03-09 15-08-40](https://user-images.githubusercontent.com/115802494/224050158-c750cf12-81a4-4c59-bb6c-bcb5d1ba7c21.png)

**Comment by reganhayward** [comment]
Out of curiosity, if you copy one of the existing files and rename it. Then use that file as "new data". Does it do the same thing?

Cos I wonder if it's something to do with the column names needing to specific. For example, locus-tag needing a space not underscore.

**Comment by hfri** [comment]
If I use existing files and rename them it works. So, it seems like it is a problem with my file. I have it attached in case you want to have a look. The Bacteroides and Salmonella files all have different column names or versions of them, so that might not be the problem. 
I converted an .odt file to csv in LibreOffice, maybe something weird happened there?
[salmonella-macro_TraDIS.csv](https://github.com/reganhayward/btheta_site/files/10933115/salmonella-macro_TraDIS.csv)

**Comment by reganhayward** [comment]
I'll take a look in the morning - but it does sound like the way your file is being encoded is the issue. 
I remember having a similar issue and just copied and pasted my data into a copy of one of the existing files. I guess that's not a long term solution though. 

Sorry to ask, but can you try exporting as a tab delimited file (TSV) and see if the same thing happens?

**Comment by hfri** [comment]
Found the mistake. In the pathway file, under value, you need to specify:
"value": {"filename": "salmonella-macro_TraDIS.csv", "seperator": "\t", **"decimal_character": "."**, ...
and in it was set to "," but in my file the deliminator was a "." . So my mistake. Sorry!

Oh and whether its tab or comma separated does not matter I think, because I tried it both.

**Comment by reganhayward** [comment]
Sweet. If you think adding some additional information in the documentation would help users, go ahead!

Also, thanks for letting me know and glad it's working 🙂

**Comment by reganhayward** [comment]
Resolved
